In [1]:
import pandas as pd

In [2]:
data = pd.read_json("./static/data/B_Project1.json")

In [4]:
data.columns = data.iloc[0]

In [5]:
data.to_json("./static/data/B_Project2.json")

Year,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
Year,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
Quarter,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,...,Q4,Q4,Q4,Q4,Q4,Q4,Q4,Q4,Q4,Q4
State,Alabama,Arizona,Arkansas,California,Colorado,Connecticut,Florida,Georgia,Hawaii,Idaho,...,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Other States 5/,United States
Colonies,7500,25000,22000,1.15e+06,13000,2900,245000,134000,17000,164000,...,125000,28000,6500,7500,87000,7000,48000,24000,11360,2.87476e+06
Max Colonies,7500,26000,22000,1540000,21000,2900,255000,139000,17000,168000,...,250000,28000,6500,7500,89000,7000,48000,25000,12560,(X)
Lost Colonies,820,6000,7500,215000,4900,140,39000,25000,1600,22000,...,25000,1900,940,750,6500,610,6500,1300,1630,412380
Added Colonies,1200,810,540,205000,1400,220,57000,29000,1200,2500,...,13000,120,10,-,330,190,210,30,100,117150
Renovated Colonies,1500,230,810,133000,190,330,38000,39000,5000,2600,...,2000,100,10,350,170,140,10,-,50,158790